import base64
from io import BytesIO
from PIL import Image as PILImage, ImageDraw, ImageFont

def ensure_pil_image(obj):
    if isinstance(obj, PILImage.Image):
        return obj
    if isinstance(obj, bytes):
        return PILImage.open(BytesIO(obj)).convert("RGB")
    if isinstance(obj, str):
        return PILImage.open(BytesIO(base64.b64decode(obj))).convert("RGB")
    return None

def add_watermark(image, text):
    water = image.copy().convert("RGBA")
    draw = ImageDraw.Draw(water)
    w,h = water.size
    font_size = max(20, w//40)
    try:
        font = ImageFont.truetype("arial.ttf", font_size)
    except:
        font = ImageFont.load_default()
    tw,th = draw.textsize(text, font=font)
    draw.text((w-tw-10, h-th-10), text, font=font, fill=(255,255,255,160))
    return water.convert("RGB")

def generate_social_caption(prompt, model):
    return f"Visualizing: {prompt}\nGenerated by {model}\n@rkjat65"
